// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package isep.rose.devstarter.domain;

import isep.rose.devstarter.domain.ManageUserProject;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ManageUserProject_Roo_Configurable {
    
    declare @type: ManageUserProject: @Configurable;
    
}
